name: Playwright e2e tests
on:
  push:
      branches: [master]
  pull_request:
      branches: [master]
    
jobs:
    playwright-e2e-tests:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node_version: 20
          - run: npm ci
          - run: npx playwright install --with-deps
          - run: npx playwright test --reporter=html
